services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoLottiePlayer\:
        resource: ../../
        exclude: ../../{ContaoManager,Model,DependencyInjection,Resources}
